'use strict';

/**
 * Canonical task work-state helpers (T-443).
 *
 * Work state deliberately lives beside, rather than instead of, the
 * FlowBoard lifecycle.  The lifecycle remains `open`, `in-progress`,
 * `review`, and `done`; this module only owns the additional, current
 * execution context.
 */

const WORK_STATES = Object.freeze(['working', 'waiting', 'blocked', 'paused']);
const WORK_STATE_SET = new Set(WORK_STATES);
const DEFAULT_WORK_STATE = 'working';
const WORK_STATE_DETAIL_FIELDS = Object.freeze([
  'reason',
  'waitingFor',
  'responsible',
  'checkAgainAt',
  'setAt',
]);

function emptyWorkStateDetails() {
  return {
    reason: null,
    waitingFor: null,
    responsible: null,
    checkAgainAt: null,
    setAt: null,
  };
}

function isPlainObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

// Datetime fields are an API contract, not free-form date labels.  Require an
// ISO-8601 date-time with an explicit timezone so a scheduler never interprets
// the same `checkAgainAt` differently on two hosts.  Legacy reads are still
// forgiving (invalid values normalize to null); writes use this strict path.
const ISO_DATETIME_RE = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d{1,3})?(Z|[+-](\d{2}):(\d{2}))$/;

function isValidDateString(value) {
  if (typeof value !== 'string' || value !== value.trim()) return false;
  const match = ISO_DATETIME_RE.exec(value);
  if (!match) return false;

  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const hour = Number(match[4]);
  const minute = Number(match[5]);
  const second = Number(match[6]);
  const offsetHour = match[8] ? Number(match[8]) : 0;
  const offsetMinute = match[9] ? Number(match[9]) : 0;
  const leapYear = year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);
  const daysInMonth = [31, leapYear ? 29 : 28, 31, 30, 31, 30,
    31, 31, 30, 31, 30, 31][month - 1];

  // Date.parse normalizes overflow (for example 2026-02-30 → March 2), so
  // validate the calendar and clock components before relying on it for the
  // timezone conversion.  Explicit timezone bounds keep scheduler inputs
  // deterministic and reject values some JS runtimes normalize differently.
  return month >= 1 && month <= 12
    && day >= 1 && day <= daysInMonth
    && hour >= 0 && hour <= 23
    && minute >= 0 && minute <= 59
    && second >= 0 && second <= 59
    // ISO-8601 permits offsets only through ±14:00.  The ±14 boundary is
    // exact; accepting e.g. +14:01 would create a timezone that the standard
    // does not define and that scheduler implementations may disagree on.
    && offsetHour >= 0 && offsetHour <= 14
    && (offsetHour < 14 || offsetMinute === 0)
    && offsetMinute >= 0 && offsetMinute <= 59
    && !Number.isNaN(new Date(value).getTime());
}

function detailError(field, message) {
  const error = new Error(`workStateDetails.${field} ${message}`);
  error.code = 'WORK_STATE_DETAILS_INVALID';
  error.status = 400;
  error.field = `workStateDetails.${field}`;
  return error;
}

/**
 * Normalize details to one stable object shape.  Reads always expose all
 * known fields; an absent optional field is represented by null.  Unknown
 * fields are intentionally dropped so metadata written by older or external
 * clients cannot become a second, competing work-state contract.
 */
function normalizeWorkStateDetails(value, {
  setAt = null,
  validate = false,
  ignoreSetAt = false,
} = {}) {
  if (value !== undefined && value !== null && !isPlainObject(value)) {
    const error = new Error('workStateDetails must be an object or null');
    error.code = 'WORK_STATE_DETAILS_INVALID';
    error.status = 400;
    error.field = 'workStateDetails';
    throw error;
  }

  const out = emptyWorkStateDetails();
  const source = isPlainObject(value) ? value : {};

  for (const field of ['reason', 'waitingFor', 'responsible']) {
    if (source[field] === undefined || source[field] === null || source[field] === '') {
      out[field] = null;
    } else if (typeof source[field] === 'string') {
      out[field] = source[field];
    } else if (validate) {
      throw detailError(field, 'must be a string or null');
    }
  }

  for (const field of ['checkAgainAt', 'setAt']) {
    // `setAt` is server-owned.  On writes, ignore both valid and malformed
    // client values and stamp the canonical server time below.  Read/migration
    // normalization keeps the legacy value so old records remain lossless.
    if (field === 'setAt' && ignoreSetAt) continue;
    const candidate = source[field];
    if (candidate === undefined || candidate === null || candidate === '') {
      out[field] = null;
    } else if (isValidDateString(candidate)) {
      // Preserve the caller's representation.  `setAt` generated by the
      // server is ISO, while preserving a valid legacy string avoids a
      // surprising migration-only value change.
      out[field] = candidate;
    } else if (validate) {
      throw detailError(field, 'must be a valid date string or null');
    }
  }

  if (!out.setAt && setAt && isValidDateString(setAt)) out.setAt = setAt;
  return out;
}

function invalidWorkState(value) {
  const error = new Error(`Invalid workState: "${value}". Must be one of: ${WORK_STATES.join(', ')}`);
  error.code = 'WORK_STATE_INVALID';
  error.status = 400;
  error.field = 'workState';
  return error;
}

function assertWorkState(value) {
  if (typeof value !== 'string' || !WORK_STATE_SET.has(value)) throw invalidWorkState(value);
  return value;
}

/**
 * Normalize stored metadata. Records without a canonical state are treated
 * as working; migration code separately converts legacy records.
 */
function normalizeStoredWorkState(flowboard = {}, { fallbackSetAt = null } = {}) {
  const source = isPlainObject(flowboard) ? flowboard : {};
  const hasCanonical = typeof source.workState === 'string' && WORK_STATE_SET.has(source.workState);
  const workState = hasCanonical ? source.workState : DEFAULT_WORK_STATE;
  const workStateDetails = normalizeWorkStateDetails(source.workStateDetails, {
    setAt: fallbackSetAt,
    validate: false,
  });
  return {
    workState,
    workStateDetails,
  };
}

/**
 * Resolve a create/update payload against the current canonical task.
 */
function resolveWorkStatePayload(payload = {}, current = null, { now = new Date().toISOString() } = {}) {
  if (Object.prototype.hasOwnProperty.call(payload, 'blocked')) {
    const error = new Error('blocked is retired; use workState');
    error.code = 'LEGACY_BLOCKED_RETIRED';
    error.status = 400;
    error.field = 'blocked';
    throw error;
  }
  const hasWorkState = Object.prototype.hasOwnProperty.call(payload, 'workState');
  const hasDetails = Object.prototype.hasOwnProperty.call(payload, 'workStateDetails');

  if (hasWorkState) assertWorkState(payload.workState);

  const currentNormalized = current
    ? normalizeStoredWorkState({
      workState: current.workState,
      workStateDetails: current.workStateDetails,
    })
    : normalizeStoredWorkState({});

  let workState = currentNormalized.workState;
  if (hasWorkState) workState = payload.workState;

  const changed = workState !== currentNormalized.workState;
  let workStateDetails;
  if (hasDetails) {
    workStateDetails = normalizeWorkStateDetails(payload.workStateDetails, {
      setAt: now,
      validate: true,
      ignoreSetAt: true,
    });
  } else if (changed || !current) {
    workStateDetails = normalizeWorkStateDetails(null, { setAt: now, validate: false });
  } else {
    workStateDetails = normalizeWorkStateDetails(currentNormalized.workStateDetails, { validate: false });
  }

  return {
    workState,
    workStateDetails,
    changed,
    hasWorkState,
    hasDetails,
  };
}

function workStateMetadata(flowboard, resolved) {
  const { blocked: _legacyBlocked, ...existing } = isPlainObject(flowboard) ? flowboard : {};
  return {
    ...existing,
    workState: resolved.workState,
    workStateDetails: resolved.workStateDetails,
  };
}

module.exports = {
  WORK_STATES,
  WORK_STATE_DETAIL_FIELDS,
  DEFAULT_WORK_STATE,
  emptyWorkStateDetails,
  isPlainObject,
  isValidDateString,
  normalizeWorkStateDetails,
  normalizeStoredWorkState,
  resolveWorkStatePayload,
  workStateMetadata,
  assertWorkState,
};
